# Default values for kfinstance.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
name: kf

# Default suffix from branch
Branch: dev
Id: 12charid9012

# Server image details
Server:
  Name: kfs
  Image: cmos/kfs
  ImageTag: latest
  Component: server
  Replicas: 2
  ImagePullPolicy: Always
  Resources:
    limits:
        cpu: 150m
        memory: 300Mi
    requests:
      cpu: 150m
      memory: 300Mi
  Service:
    externalPort: 3000
    internalPort: 3000
    portType: ClusterIP #can be NodePort, ExternalName, LoadBalancer, ClusterIP

# Worker
Worker:
  Name: kfw
  Image: cmos/kfw
  ImageTag: latest
  Component: worker
  Replicas: 2
  ImagePullPolicy: Always
  Resources:
    limits:
      cpu: 150m
      memory: 300Mi
    requests:
      cpu: 150m
      memory: 300Mi

# Notification
Notification:
  Enabled: false
  Name: kfn
  Image: cmos/kfn
  ImageTag: latest
  Component: notification
  Replicas: 1
  ImagePullPolicy: Always
  Resources:
    limits:
      cpu: 150m
      memory: 300Mi
    requests:
      cpu: 150m
      memory: 300Mi
  Service:
    externalPort: 3000
    internalPort: 3000
    portType: ClusterIP #can be NodePort, ExternalName, LoadBalancer, ClusterIP

# Dedicated mongo instance
Mongo:
  Name: kfmongo
  Image: mongo:4.0
  Resources:
    limits:
      cpu: 150m
      memory: 300Mi
    requests:
      cpu: 150m
      memory: 300Mi
  Volumes:
    Capacity: 2Gi
    HostPath: "/mnt/data/instances/mongodb"
  ServiceName: kfm
  ServicePort: 27017


# ElasticSearch config

ElasticSearch:
  # if Enabled: true Monstache will be also started
  Enabled: false
  ES_URI: "elasticsearch-ingest:9200"
  ES_VERSION: "6.x"
  ES_FORCE_BUILD_IDF: "enabled"

# dedicated ES sync instance with Monstache
Monstache:
  Name: kfmonstache
  Image: rwynn/monstache:4.8.0
  Resources:
    limits:
      cpu: 100m
      memory: 150Mi
    requests:
      cpu: 100m
      memory: 150Mi

# RBAC
rbac:
  install: true
  serviceAccountName: default
  # RBAC api version (currently either v1beta1 or v1alpha1)
  apiVersion: v1beta1
  roleRef: cluster-admin

# languages
Languages: "en,nl,fr,ro"

# PASSWORD SETTINGS
Password:
  minAmountChars: "8"
  minAmountLetters: "1"
  minAmountNumbers: "1"

# DEBUG
DEBUG: none
