apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "mongo-fullname" .}}
  labels:
    app: {{ template "fullname" . }}
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ template "mongo-fullname" . }}
    id: {{ .Values.Id }}
    branch: {{ .Values.Branch }}
spec:
  capacity:
    storage: {{ .Values.Mongo.Volumes.Capacity }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ template "mongo-hostpath" . }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "mongo-fullname" .}}
  labels:
    app: {{ template "fullname" . }}
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ template "mongo-fullname" . }}
    id: {{ .Values.Id }}
    branch: {{ .Values.Branch }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.Mongo.Volumes.Capacity }}
  selector:
    matchLabels:
      component: {{ template "mongo-fullname" . }}


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "mongo-fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ template "mongo-fullname" . }}
    id: {{ .Values.Id }}
    branch: {{ .Values.Branch }}
    name: {{ template "mongo-fullname" . }}
spec:
  replicas: 1
  selector:
     matchLabels:
        app: {{ template "fullname" . }}
        component: {{ template "mongo-fullname" . }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        component: {{template "mongo-fullname" . }}
        name: {{ template "mongo-controller-port" .}}
    spec:
      containers:
      - image: "{{ .Values.Mongo.Image }}"
        name: {{ template "mongo-fullname" . }}
        ports:
        - name:  {{ template "mongo-controller-port" .}}
          containerPort: {{ .Values.Mongo.ServicePort }}
          hostPort: {{ .Values.Mongo.ServicePort }}
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
{{ toYaml .Values.Mongo.Resources | indent 12 }}
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: {{ template "mongo-fullname" .}}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "fullname" . }}
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ template "mongo-fullname" . }}
    id: {{ .Values.Id }}
    branch: {{ .Values.Branch }}
    role: service
    name: {{ template "mongo-controller-port" . }}
  name: {{ template "mongo-service" . }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.Mongo.ServicePort }}
      targetPort: {{ .Values.Mongo.ServicePort }}
  selector:
    name: {{ template "mongo-controller-port" . }}