apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "worker-fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ template "worker-fullname" . }}
    id: {{ .Values.Id }}
    branch: {{ .Values.Branch }}
spec:
  replicas: {{ default 1 .Values.Worker.Replicas}}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      component:  {{ template "worker-fullname" . }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{default 1 .Values.Worker.Replicas}}
      maxUnavailable: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        component:  {{ template "worker-fullname" . }}
    spec:
      containers:
      - name: {{ template "worker-fullname" . }}
        image: "{{ .Values.Worker.Image }}:{{ .Values.Worker.ImageTag }}"
        imagePullPolicy: {{ .Values.Worker.ImagePullPolicy }}
        ports:
          - containerPort: {{ .Values.Server.Service.internalPort }}
        env:
        - name: NODE_ENV
          value: "production"
        {{- if .Values.ElasticSearch.Enabled }}
        - name: ES_URI
          value: {{ .Values.ElasticSearch.ES_URI }}
        - name: ES_VERSION
          value: {{ .Values.ElasticSearch.ES_VERSION }}
        - name: ES_FORCE_BUILD_IDF
          value: {{ .Values.ElasticSearch.ES_FORCE_BUILD_IDF }}
        {{- else}}
        - name: ES_URI
          value: "elasticNotEnabled:9200"
        {{- end}}
        - name: AS3_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              key: AS3_ACCESS_KEY
              name: kf-s3-bucket-config
        - name: AS3_SIGNATURE_VERSION
          valueFrom:
            configMapKeyRef:
              key: AS3_SIGNATURE_VERSION
              name: kf-s3-bucket-config
        - name: AS3_REGION
          valueFrom:
            configMapKeyRef:
              key: AS3_REGION
              name: kf-s3-bucket-config
        - name: AS3_BUCKET
          valueFrom:
            configMapKeyRef:
              key: AS3_BUCKET
              name: kf-s3-bucket-config
        - name: AS3_MAX_FILE_SIZE
          valueFrom:
            configMapKeyRef:
              key: AS3_MAX_FILE_SIZE
              name: kf-s3-bucket-config
        - name: AS3_MAX_FILE_SIZE_LIMIT
          valueFrom:
            configMapKeyRef:
              key: AS3_MAX_FILE_SIZE_LIMIT
              name: kf-s3-bucket-config
        - name: AS3_MAX_TOTAL_FILE_SIZE
          valueFrom:
            configMapKeyRef:
              key: AS3_MAX_TOTAL_FILE_SIZE
              name: kf-s3-bucket-config
        - name: AS3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AS3_SECRET_ACCESS_KEY
              name: kf-s3-bucket-secret
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: kfcloudinary
              key: cloudname
        - name: CLOUDINARY_API_KEY
          valueFrom:
            secretKeyRef:
              name: kfcloudinary
              key: api_key
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: kfcloudinary
              key: api_secret
        - name: TRUE_FALSE
          value: "0"
        - name: MULTIPLE_CHOICE
          value: "1"
        - name: SELF_EVALUATION
          value: "0"
        - name: ORDER_BITS
          value: "0"
        - name: ORDER_SECTION_BITS
          value: "0"
        - name: MATCH_IMAGE_WITH_SHEET_TITLES
          value: "0"
        - name: MATCH_BITS_TO_SHEET
          value: "0"
        - name: MATCH_SHEET_TITLE_WITH_IMAGES
          value: "0"
        - name: MONGO_DB
          value: {{ template "mongo-db" . }}
        - name: SUBDOMAIN
        {{- if .Values.SUBDOMAIN}}
          value: {{ .Values.SUBDOMAIN}}
        {{- else}}
          value: "kf-{{ .Values.Id}}"
        {{- end}}
        - name: DEBUG
          value: {{ .Values.DEBUG}}
        - name: MONGO_URI
          value: {{ template "mongo-uri" . }}
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_IP
          value: "kfredis-redis-ha-master-svc"
        - name: PASSWORD_MIN_AMOUNT_CHARS
          value: {{ .Values.Password.minAmountChars | quote}}
        - name: PASSWORD_MIN_AMOUNT_LETTERS
          value: {{ .Values.Password.minAmountLetters | quote}}
        - name: PASSWORD_MIN_AMOUNT_NUMBERS
          value: {{ .Values.Password.minAmountNumbers | quote }}
        - name: DEFAULT_OWNER_GROUP
          value: "OWNER"
        - name: DEFAULT_USER_GROUP
          value: "USER"
        - name: LANGUAGE_FIELDNAME
          value: "language"
        - name: LANGUAGES
          value: {{ .Values.Languages }}
        - name: ACCOUNT_OWNER_EMAIL
        {{ if .Values.AccountOwnerEmail }}
          value: {{ .Values.AccountOwnerEmail }}
        {{ else }}
          value: "admin-{{ .Values.Id }}@knowledgeflow.io"
        {{ end }}
        - name: ACCOUNT_OWNER_PASSWORD
        {{ if .Values.AccountOwnerPassword }}
          value: {{ .Values.AccountOwnerPassword }}
        {{ else }}
          value: {{ randAlphaNum 10 | b64enc | quote }}
        {{ end }}
        - name: USERNAME_IS_EMAIL
          value: "0"
        - name: REALTIME_SERVER_ENABLED
        {{- if eq .Values.Notification.Enabled true }}
          value: "true"
        {{- else }}}
          value: "false"
        {{- end }}
        resources:
{{ toYaml .Values.Worker.Resources | indent 12 }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.Server.Service.internalPort }}
          initialDelaySeconds: 120
          periodSeconds: 11
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.Server.Service.internalPort }}
          initialDelaySeconds: 10
          periodSeconds: 5
